language: cpp
dist: bionic
compiler: gcc
os: linux

script: 
- g++ -o conjugator ./spanish1/src/content/ArgsParser.cpp ./spanish1/src/content/Component.cpp ./spanish1/src/content/Content.cpp ./spanish1/src/content/FileReader.cpp ./spanish1/src/content/Parser.cpp ./spanish1/src/content/Rule.cpp ./spanish1/src/content/Selector.cpp ./spanish1/src/content/VerbBase.cpp ./spanish1/src/content/Word.cpp ./spanish1/src/main/spanish1.cpp
- g++  -o lookup ./LookupVerb/src/FileReader.cpp ./LookupVerb/src/InfContent.cpp ./LookupVerb/src/LookupVerb.cpp ./LookupVerb/src/Parser.cpp
- g++  -o unittest ./TestSuite/src/main.cpp
- ./unittest
